-- 
--  Sea el siguiente conjunto de tablas en una base de datos:
-- 
--    tbl0
--    ------------------------
--    K0  CHAR(1)
--    c01 INT
--    c02 INT
--    c03 CHAR(4)
--    c04 FLOAT
--        
--    tbl1
--    ------------------------
--    K0  CHAR(1)
--    K1  INT
--    c12 FLOAT
--    c13 INT
--    c14 DATE
--    c15 FLOAT
--    c16 CHAR(4)
--
--    tbl2
--    ------------------------
--    K1  INT,
--    c21 FLOAT,
--    c22 INT,
--    c23 DATE,
--    c24 FLOAT,
--    c25 CHAR(5)
--
--  Escriba una consulta que retorne los campos K0 y c16
--  para los registros de la tabla tbl1 para los que la 
--  columna c16 empieza por la misma letra de la columna K0.
--
--  Rta/
--    K0   c16
--  0  E  EGFD
--  1  B  BDEE
--  2  C  CCCE
--
--  >>> Escriba su codigo a partir de este punto <<<
-- 
-- La función substr() toma tres argumentos: 
-- la cadena de entrada, la posición inicial y la longitud de la subcadena que se va a extraer.
-- estamos extrayendo una subcadena de longitud 1, que es simplemente el primer carácter de la cadena.
-- substr(c16, 1, 1) extrae el primer carácter de la columna c16
SELECT K0, c16
FROM tbl1
WHERE substr(c16, 1, 1) = substr(K0, 1, 1);